create table if not exists public.months (
  id text primary key,
  year integer not null,
  month integer not null check (month between 1 and 12),
  label text not null,
  days_in_month integer not null check (days_in_month between 28 and 31),
  created_at timestamptz not null default now()
);

create table if not exists public.packages (
  id bigint generated by default as identity primary key,
  name text not null,
  price integer not null default 0,
  doc integer not null default 0,
  nur_phy integer not null default 0,
  nur integer not null default 0,
  phy integer not null default 0,
  psy integer not null default 0,
  med integer not null default 0,
  sort_order integer not null default 0
);

create table if not exists public.month_patients (
  id bigint generated by default as identity primary key,
  month_id text not null references public.months(id) on delete cascade,
  patient_id integer not null,
  name text not null,
  subscriber text not null default '',
  pkg_idx integer not null default -1,
  med_given integer not null default 0,
  visits_json jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  unique (month_id, patient_id)
);

create index if not exists month_patients_month_sort_idx
  on public.month_patients (month_id, sort_order, patient_id);

alter table public.months enable row level security;
alter table public.packages enable row level security;
alter table public.month_patients enable row level security;

comment on table public.months is 'Monthly visit-sheet definitions migrated from the local SQLite database.';
comment on table public.packages is 'Package definitions migrated from the local SQLite database.';
comment on table public.month_patients is 'Patient-month records; visits_json contains one five-value array per calendar day.';
