-- Migration: Unify packages to plans schema and add health plan accounting attributes
-- Safe to run multiple times: uses IF NOT EXISTS and checks

-- 1. Rename packages table to plans if packages exists and plans does not
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'packages' AND table_schema = 'public')
     AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'plans' AND table_schema = 'public') THEN
    ALTER TABLE public.packages RENAME TO plans;
  END IF;
END $$;

-- 2. If neither table existed (clean install), create plans table
CREATE TABLE IF NOT EXISTS public.plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  price integer NOT NULL DEFAULT 0,
  doc integer NOT NULL DEFAULT 0,
  nur_phy integer NOT NULL DEFAULT 0,
  nur integer NOT NULL DEFAULT 0,
  phy integer NOT NULL DEFAULT 0,
  psy integer NOT NULL DEFAULT 0,
  med integer NOT NULL DEFAULT 0,
  sv integer NOT NULL DEFAULT 0,
  flu integer NOT NULL DEFAULT 0,
  opd integer NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0
);

-- 3. Add accounting and extended health plan columns
ALTER TABLE public.plans
  ADD COLUMN IF NOT EXISTS billing_cycle text NOT NULL DEFAULT 'monthly',
  ADD COLUMN IF NOT EXISTS revenue_account_id uuid REFERENCES public.accounts(id),
  ADD COLUMN IF NOT EXISTS lab_tests integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

-- 4. Enable RLS on plans
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'plans' AND policyname = 'service_role_all'
  ) THEN
    CREATE POLICY service_role_all ON public.plans
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

-- 5. Backward compatibility view so any legacy queries pointing to public.packages still work seamlessly
CREATE OR REPLACE VIEW public.packages AS SELECT * FROM public.plans;

-- 6. In month_patients, support plan_id alongside package_id
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'month_patients' AND column_name = 'plan_id'
  ) THEN
    ALTER TABLE public.month_patients ADD COLUMN plan_id bigint REFERENCES public.plans(id);
  END IF;
END $$;

-- Synchronize existing values from package_id to plan_id if package_id exists
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'month_patients' AND column_name = 'package_id'
  ) THEN
    UPDATE public.month_patients SET plan_id = package_id WHERE plan_id IS NULL AND package_id IS NOT NULL;
  END IF;
END $$;

-- 7. Trigger to keep package_id and plan_id in sync automatically on month_patients
CREATE OR REPLACE FUNCTION public.sync_month_patient_plan_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.plan_id IS NOT NULL AND NEW.package_id IS NULL THEN
    NEW.package_id := NEW.plan_id;
  ELSIF NEW.package_id IS NOT NULL AND NEW.plan_id IS NULL THEN
    NEW.plan_id := NEW.package_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_month_patient_plan_id ON public.month_patients;
CREATE TRIGGER trg_sync_month_patient_plan_id
BEFORE INSERT OR UPDATE ON public.month_patients
FOR EACH ROW EXECUTE FUNCTION public.sync_month_patient_plan_id();
